from playwright.sync_api import Page


class HomePage:
    def __init__(self, page: Page):
        self.page = page
        self.url = "https://www.dharwadhubballitutor.com/"
        self.google_ratings_link = self.page.get_by_text("4.9 Google Ratings Read Our")
        self.trained_students_link = self.page.get_by_text("+ Trained Students")
        self.experienced_trainers_link = self.page.get_by_text("Experienced Trainers Minimum")
        self.guaranteed_placement_link = self.page.get_by_text("Guaranteed Placement Unlimited interview opportunities")
        self.explore_everything_link = self.page.get_by_text("Explore Everything")
        self.discover_programs_heading = self.page.get_by_role("heading", name="Discover Our Programs")
        self.trainings_heading = self.page.get_by_role("heading", name="Trainings")
        self.trainings_explore_courses_link = self.page.get_by_text("Trainings Explore our programs Explore Courses")
        self.internships_heading = self.page.get_by_role("heading", name="Internships")
        self.internships_explore_courses_link = self.page.get_by_text("Internships Explore our programs Explore Courses")
        self.services_heading = self.page.get_by_role("heading", name="Services")
        self.services_explore_courses_link = self.page.get_by_text("Services Professional IT Services Explore Courses")
        self.jobs_heading = self.page.get_by_role("heading", name="Jobs", exact=True)
        self.jobs_explore_courses_link = self.page.get_by_text("Jobs Latest Career Opportunities Explore Courses")
        self.workshops_heading = self.page.get_by_role("heading", name="Workshops")
        self.workshops_explore_courses_link = self.page.get_by_text("Workshops Hands-on Practical Sessions Explore Courses")
        self.blogs_heading = self.page.get_by_role("heading", name="Blogs")
        self.blogs_explore_courses_link = self.page.get_by_text("Blogs Latest Articles & Updates Explore Courses")
        self.accreditations_heading = self.page.get_by_role("heading", name="Our Official Accreditations")
        self.popular_courses_heading = self.page.get_by_role("heading", name="Our Most Popular Courses")
        self.explore_best_selling_link = self.page.get_by_text("Explore our best-selling")
        self.live_projects_heading = self.page.get_by_role("heading", name="Our Live Projects")
        self.nwkrtc_bi_dashboard_heading = self.page.get_by_role("heading", name="NWKRTC – BI Dashboard")
        self.ace_decors_erp_application_heading = self.page.get_by_role("heading", name="ACE DECORS – ERP Application")
        self.recon_event_analytics_heading = self.page.get_by_role("heading", name="RECON – Event Analytics")
        self.oxford_coaching_dynamic_web_heading = self.page.get_by_role("heading", name="Oxford Coaching – Dynamic Web")
        self.angadi_coaching_web_heading = self.page.get_by_role("heading", name="Angadi Coaching – Web")
        self.anjuman_bca_bba_institute_heading = self.page.get_by_role("heading", name="Anjuman BCA & BBA Institute")
        self.our_alumni_work_at_heading = self.page.get_by_role("heading", name="Our Alumni Work At")
        self.alumni_placement_company_5 = self.page.get_by_role("img", name="Alumni placement company 5 —")
        self.alumni_placement_company_6 = self.page.get_by_role("img", name="Alumni placement company 6 —")
        self.tvg_agency_img = self.page.get_by_role("img", name="TVG Agency —")
        self.contentinfo_text = self.page.get_by_role("contentinfo").get_by_text("DharwadHubballiTutor is one")
        self.home_about_contact = self.page.get_by_text("Home About Contact")
        self.terms_and_conditions_link = self.page.get_by_role("link", name="→ Terms and Conditions")
        self.privacy_policy_link = self.page.get_by_role("link", name="→ Privacy Policy")
        self.contact_locations_heading = self.page.get_by_role("heading", name="Contact & Locations")
        self.dharwad_branch = self.page.get_by_text("Dharwad Branch")
        self.hubballi_branch = self.page.get_by_text("Hubballi Branch")
        self.belagavi_branch = self.page.get_by_text("Belagavi Branch")
        self.contact_locations_plus = self.page.get_by_text("Contact & Locations +")   
        